import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import "./globals.css";
import { Provider } from "./graphql/provider";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const locale = await getLocale();
   const messages = await getMessages();
   return (
      <html lang={locale} suppressHydrationWarning={true}>
         <body className={inter.className}>
            <NextIntlClientProvider messages={messages}>
               <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                  {/* Burada ApolloProvider yerine yeni bir dosyada prodiver oluşturulma sebebi apollonun client side da çalışmak istemesinden kaynaklı */}
                  <Provider>{children}</Provider>
                  <Toaster />
               </ThemeProvider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
