name: Delete Old Reservations

on:
   schedule:
      - cron: "0 */2 * * *"
   workflow_dispatch:

jobs:
   delete-reservations:
      runs-on: ubuntu-latest
      steps:
         - name: Make GraphQL Request to Hasura
           run: |
              curl -X POST https://active-moccasin-54.hasura.app/v1/graphql \
              -H "Content-Type: application/json" \
              -H "x-hasura-admin-secret: ${{ secrets.HASURA_ADMIN_SECRET }}" \
              -d '{"query":"mutation { delete_reservations(where: { created_at: {_lt: \"now() - \u0027interval 2 hours\u0027::interval\"}, payment: {_eq: false} }) { affected_rows } }"}'
